type = "CNN"
name = "CNN"
train_dir = "data/spectrograms/combined"
test_dir = "data/spectrograms_test/combined"
img_width = 224
img_height = 224
batch_size=32
seed_value = 32
learning_rate=0.0001
momentum = 0.8
epochs = 50